name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.7', '1.8, 'nightly']
        # julia-arch: [x64, x86]
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        julia-arch: [x64]
        os: [ubuntu-latest, macOS-latest]
        exclude:
          - os: macOS-latest
            julia-version: ['1.7', 'nightly']

    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
